if(NOT DEFINED MAIN_SOURCE OR NOT DEFINED OPTIONS_HEADER)
    message(FATAL_ERROR "MAIN_SOURCE and OPTIONS_HEADER are required")
endif()

file(READ "${MAIN_SOURCE}" main_source)
string(REGEX MATCHALL "==[ \t\r\n]*\"--[A-Za-z0-9-]+\"" parser_matches "${main_source}")
set(parser_options)
foreach(match IN LISTS parser_matches)
    string(REGEX REPLACE ".*\"(--[A-Za-z0-9-]+)\".*" "\\1" option "${match}")
    list(APPEND parser_options "${option}")
endforeach()
list(REMOVE_DUPLICATES parser_options)
list(SORT parser_options)

file(READ "${OPTIONS_HEADER}" options_header)
string(FIND "${options_header}" "kKnownCommandLineOptions{{" known_start)
if(known_start EQUAL -1)
    message(FATAL_ERROR "Could not locate kKnownCommandLineOptions in ${OPTIONS_HEADER}")
endif()
string(SUBSTRING "${options_header}" ${known_start} -1 known_tail)
string(FIND "${known_tail}" "}};" known_end)
if(known_end EQUAL -1)
    message(FATAL_ERROR "Could not locate the end of kKnownCommandLineOptions in ${OPTIONS_HEADER}")
endif()
string(SUBSTRING "${known_tail}" 0 ${known_end} known_block)
string(REGEX MATCHALL "\"--[A-Za-z0-9-]+\"" known_matches "${known_block}")
set(known_options)
foreach(match IN LISTS known_matches)
    string(REGEX REPLACE "\"(--[A-Za-z0-9-]+)\"" "\\1" option "${match}")
    list(APPEND known_options "${option}")
endforeach()
list(LENGTH known_options known_count_with_duplicates)
list(REMOVE_DUPLICATES known_options)
list(LENGTH known_options known_count)
if(NOT known_count EQUAL known_count_with_duplicates)
    message(FATAL_ERROR "kKnownCommandLineOptions contains duplicate entries")
endif()
list(SORT known_options)

set(missing_options)
foreach(option IN LISTS parser_options)
    if(NOT option IN_LIST known_options)
        list(APPEND missing_options "${option}")
    endif()
endforeach()
set(extra_options)
foreach(option IN LISTS known_options)
    if(NOT option IN_LIST parser_options)
        list(APPEND extra_options "${option}")
    endif()
endforeach()

if(missing_options OR extra_options)
    message(FATAL_ERROR
        "Known CLI option table is out of sync. Missing: [${missing_options}] Extra: [${extra_options}]")
endif()

message(STATUS "Known CLI option table matches ${known_count} parser options")
